# Generated by Django 4.0.5 on 2022-07-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_travel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travel',
        ),
    ]
